artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts\data_ingestion
  source_destination: C:\Users\rvaib\Downloads\archive (1).zip
  local_data_file: artifacts\data_ingestion\data.zip
  unzip_dir: artifacts\data_ingestion


model_trainer:
  root_dir: artifacts\model_trainer
  train_data_path: artifacts\data_ingestion\train
  test_data_path: artifacts\data_ingestion\test
  model_name: model.h5

model_evaluation:
  root_dir: artifacts\model_evaluation
  train_data_path: artifacts\data_ingestion\train
  test_data_path: artifacts\data_ingestion\test
  metric_file_name: artifacts\model_evaluation\metrics.json
  model_path: artifacts\model_trainer\model.h5
  mlflow_uri: https://dagshub.com/Rvaibhavv/kidney-Disease-Dl-Classifier.mlflow
  

  